name = "ikis-backend"
main = "src/index.ts"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
DEV_AUTH = "false"
GOOGLE_CLIENT_ID = "123747138376-16oc38ijefrpah2vc0k9o5o4vkeg0okm.apps.googleusercontent.com"

[[d1_databases]]
binding = "DB"
database_name = "ikis"
database_id = "e7a50072-3af4-423c-a517-0523d8ac0f28"
migrations_dir = "drizzle/migrations"
